version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    command: ["sh", "-c", "ollama pull llama2 && ollama pull mistral"]
  python_app:
    build:
      context: ./python_app
    container_name: my_fastapi_app
    ports:
      - "8000:8000"
  nodejs_app:
    build:
      context: ./nodejs-api
    container_name: my_nodejs_app
    ports:
      - "3000:3000"
volumes:
  ollama:
